---
title: "Skopje Map"
author: novica
output: html
---

```{r}
#| label: libraries
#| warning: false
box::use(
  cowplot[ggdraw, draw_image],
  ggplot2[annotate, ggplot, coord_sf, element_blank, geom_sf, ggsave, theme],
  ggthemes[theme_solarized],
  osmdata[add_osm_feature, getbb, opq, osmdata_sf],
  png[readPNG]
)
```

## Data

We use data from [OpenStreetMap](https://www.openstreetmap.org). The objects are stored as `RDS` files in `data` because there  is no need to query for it each time this notebook is run.

```{r}
#| label: get-coordinates
#| eval: false
 
coordinates <- getbb("Skopje North Macedonia")
```

```{r}
#| label: get-streets
#| eval: false

streets <- getbb("Skopje North Macedonia") |>
  opq()|>
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", 
                            "secondary", "tertiary")) |>
  osmdata_sf()
streets
```

```{r}
#| label: get-small-streets
#| eval: false
 
small_streets <- getbb("Skopje North Macedonia")|>
  opq()|>
  add_osm_feature(key = "highway", 
                  value = c("residential", "living_street",
                            "unclassified",
                            "service", "footway")) |>
  osmdata_sf()
```

```{r}
#| label: get-rivers
#| eval: false
 
river <- getbb("Skopje North Macedonia") |>
  opq()|>
  add_osm_feature(key = "waterway", value = "river") |>
  osmdata_sf()
```

```{r}
#| label: save-data
#| eval: false

saveRDS(coordinates, 'data/coordinates.rds')
saveRDS(streets, 'data/streets.rds')
saveRDS(small_streets, 'data/small_streets.rds')
saveRDS(rivers, 'data/rivers.rds')
```

### Load saved data (start here)

```{r}
#| label: load-data

coordinates <- readRDS("data/coordinates.rds")
streets <- readRDS("data/streets.rds")
small_streets <- readRDS("data/small_streets.rds")
rivers <- readRDS("data/river.rds")

```

## Plot

```{r}
#| label: basic-plot

ggplot() +
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .4,
          alpha = .8) 
  
```

```{r}
#| label: all-layers-plot

ggplot() +
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .4,
          alpha = .8) +
  geom_sf(data = small_streets$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .4,
          alpha = .6) +
  geom_sf(data = rivers$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .2,
          alpha = .5) +
  coord_sf(xlim = coordinates[1, ], 
           ylim = coordinates[2, ],
           expand = FALSE) 
```

```{r}
#| label: construct-final-lot
p <- ggplot() +
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .6,
          alpha = .8) +
  geom_sf(data = small_streets$osm_lines,
          inherit.aes = FALSE,
          color = "azure4",
          size = .4,
          alpha = .6) +
  geom_sf(data = rivers$osm_lines,
          inherit.aes = FALSE,
          color = "darkturquoise",
          size = 1.2,
          alpha = .8) +
  coord_sf(xlim = coordinates[1, ], 
           ylim = coordinates[2, ],
           expand = TRUE) 
```  
  


```{r}
#| label: add-theme
p <- p + theme_solarized(light=TRUE) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank())
```

```{r}
#| label: annotate
# Center coordinates: x = 21.42656, y = 42.00299
p <- p + annotate("text", 
                  x = 21.42656, 
                  y = 41.945, 
                  label = "С К О П Ј Е\n42°0′N / 21°26′E", 
                  color = "darkturquoise", 
                  size = 5,
                  hjust = 0.5,
                  family = "mono",
                  fontface = "bold")
```

```{r}
#| label: add-coat-of-arms

logo_file <- readPNG("./coat.png")

ggdraw(p) + 
  draw_image(logo_file, x = 1, y = 1, hjust = 6.5, vjust = 4.3, width = 0.13, height = 0.2)
```

```{r}
#| label: save-image
ggsave("map.png", width = 8, height = 4.9)
```

